// questions.js
const bancoPorNiveles = [
{
    estacion: 1, // ESTACIÓN 1: BÁSICA (Preguntas 1 a 27 del Excel)
    preguntas: [
    { enunciado: "¿Cuál es la modalidad de selección que por regla general se utiliza para la contratación de obra pública en INVIAS?", opcionA: "Contratación Directa", opcionB: "Licitación Pública", opcionC: "Selección Abreviada de Menor Cuantía", correcta: "Opción B" },
    { enunciado: "¿Qué herramienta transaccional del Estado permite publicar, evaluar y adjudicar en línea los procesos contractuales de la entidad?", opcionA: "SIIF Nación", opcionB: "SECOP II", opcionC: "Sinaf", correcta: "Opción B" },
    { enunciado: "¿Qué significan las siglas PAA, documento obligatorio donde se consolidan los planes de contratación anuales?", opcionA: "Plan Anual de Adquisiciones", opcionB: "Presupuesto de Asfalto Anual", opcionC: "Plan de Anticipos Autorizados", correcta: "Opción A" },
    { enunciado: "¿Cuál es el registro donde se inscriben, califican y clasifican las personas naturales o jurídicas que pretenden contratar con el Estado?", opcionA: "RUT (Registro Único Tributario)", opcionB: "RUP (Registro Único de Proponentes)", opcionC: "Runt", correcta: "Opción B" },
    { enunciado: "En un proceso contractual de INVIAS, ¿cuál es la etapa donde se realizan los estudios previos y la planeación del proceso?", opcionA: "Etapa Contractual", opcionB: "Etapa Precontractual", opcionC: "Etapa Postcontractual", correcta: "Opción B" },
    { enunciado: "De acuerdo con la Ley 80, ¿cuál de los siguientes es un principio fundamental de la contratación estatal?", opcionA: "Principio de Transparencia", opcionB: "Principio de Exclusividad", opcionC: "Principio de Reserva Sumarial", correcta: "Opción A" },
    { enunciado: "¿Qué sigla define el valor máximo que la entidad puede destinar para la contratación de un bien, obra o servicio?", opcionA: "CDP", opcionB: "PO (Presupuesto Oficial)", opcionC: "RP", correcta: "Opción B" },
    { enunciado: "Las observaciones formuladas por los interesados a los proyectos de pliego de condiciones tienen como fin:", opcionA: "Suspender de manera definitiva el proceso de selección", opcionB: "Retroalimentar a la entidad para ajustar y mejorar las reglas del futuro pliego definitivo", opcionC: "Asignar directamente el contrato a un oferente", correcta: "Opción B" },
    { enunciado: "¿Ante qué escenario contractual se utiliza comúnmente la modalidad de Mínima Cuantía?", opcionA: "Contratos cuyo valor no excede el 10% de la menor cuantía de la entidad", opcionB: "Grandes obras de infraestructura vial como túneles o viaductos", opcionC: "Contratación de urgencia manifiesta exclusivamente", correcta: "Opción A" },
    { enunciado: "El Plan Anual de Adquisiciones (PAA) debe ser publicado por la entidad estatal en:", opcionA: "La página web de la Contraloría General de la República.", opcionB: "La plataforma SECOP a más tardar el 31 de enero de cada año.", opcionC: "El Diario Oficial de la Nación únicamente.", correcta: "Opción B" },
    { enunciado: "Las adendas a los pliegos de condiciones son documentos oficiales expedidos por la entidad para:", opcionA: "Modificar los pliegos de condiciones ya publicados, aclarando o variando sus términos de forma legal.", opcionB: "Cancelar definitivamente el proceso de selección sin dar explicaciones.", opcionC: "Sancionar económicamente a los proponentes que hicieron demasiadas observaciones.", correcta: "Opción A" },
    { enunciado: "¿Cuál de los siguientes NO constituye un requisito habilitante dentro de un pliego de condiciones?", opcionA: "La capacidad jurídica y de representación de la empresa.", opcionB: "El menor precio ofertado por el proponente.", opcionC: "La capacidad financiera y organizacional del interesado.", correcta: "Opción B" },
    { enunciado: "En el SECOP II, cuando un proponente requiere solicitar aclaraciones sobre el pliego, debe hacerlo a través de:", opcionA: "Un correo electrónico privado enviado al Director General.", opcionB: "El módulo de mensajes y observaciones integrado dentro del mismo proceso en la plataforma.", opcionC: "Una llamada telefónica a la línea de servicio al ciudadano del instituto.", correcta: "Opción B" },
    { enunciado: "El documento soporte técnico donde la entidad justifica la conveniencia, el objeto, el valor y los riesgos de la contratación se denomina:", opcionA: "Estudios y Documentos Previos.", opcionB: "Acta de Adjudicación.", opcionC: "Informe de Evaluación Definitivo.", correcta: "Opción A" },
    { enunciado: "La sigla 'EAL' utilizada en el análisis económico precontractual de los proponentes significa:", opcionA: "Evaluación de Activos Líquidos.", opcionB: "Experiencia Adicional Lograda.", opcionC: "Estructura de Alerta de Liquidación.", correcta: "Opción B" },
    { enunciado: "Cuando un proceso se adelanta por 'Licitación Pública', cualquier interesado que cumpla el pliego puede presentar oferta. Esto responde al principio de:", opcionA: "Libre Concurrencia o Selección Objetiva.", opcionB: "Secreto Contractual Estatal.", opcionC: "Autonomía Discrecional de la Entidad.", correcta: "Opción A" },
    { enunciado: "Los pliegos de condiciones publicados en borrador para recibir comentarios de la ciudadanía se conocen técnicamente como:", opcionA: "Proyecto de Pliego de Condiciones.", opcionB: "Pliego de Condiciones Definitivo.", opcionC: "Anexo Técnico Operativo.", correcta: "Opción A" },
    { enunciado: "¿Qué entidad del Gobierno Nacional actúa como el ente rector de la contratación pública y administra el SECOP en Colombia?", opcionA: "El Ministerio de Transporte.", opcionB: "Colombia Compra Eficiente (CCE).", opcionC: "La Superintendencia de Sociedades.", correcta: "Opción B" },
    { enunciado: "El número mínimo de opciones de respuesta que debe contener una pregunta de selección múltiple según las buenas prácticas técnico-jurídicas implementadas es:", opcionA: "Cinco opciones obligatorias.", opcionB: "Tres opciones bien estructuradas (Única respuesta correcta).", opcionC: "Dos opciones únicamente.", correcta: "Opción B" },
    { enunciado: "El Estatuto General de Contratación de la Administración Pública en Colombia está recopilado principalmente en:", opcionA: "La Ley 80 de 1993 y la Ley 1150 de 2007.", opcionB: "El Código de Procedimiento Penal.", opcionC: "La Ley 100 de 1993 exclusivamente.", correcta: "Opción A" },
    { enunciado: "La capacidad jurídica de un proponente extranjero que desea participar en un proceso vial en Colombia se verifica mediante:", opcionA: "La cédula de extranjería de su representante legal únicamente.", opcionB: "El documento equivalente que acredite su existencia y representación legal, debidamente apostillado o legalizado.", opcionC: "Una carta de recomendación de otra entidad estatal colombiana.", correcta: "Opción B" },
    { enunciado: "En la plataforma transaccional SECOP II, los proponentes presentan sus ofertas de manera:", opcionA: "Física, radicando carpetas de papel en la ventanilla del instituto.", opcionB: "Virtual, cargando los documentos directamente en la plataforma antes de la hora de cierre.", opcionC: "Mixta, enviando un correo y radicando los CD físicos en la entidad.", correcta: "Opción B" },
    { enunciado: "¿Qué documento expedido por la entidad oficial marca el inicio formal y legal para la presentación de ofertas?", opcionA: "El Acto Administrativo de Apertura del proceso de selección.", opcionB: "La publicación del PAA del año anterior.", opcionC: "El Informe de Evaluación Preliminar.", correcta: "Opción A" },
    { enunciado: "Las exigencias de experiencia e indicadores financieros que un proponente debe cumplir para no ser rechazado se denominan:", opcionA: "Criterios de Ponderación de Puntaje.", opcionB: "Requisitos Habilitantes.", opcionC: "Factores de Desempate Técnico.", correcta: "Opción B" },
    { enunciado: "Cuando un proponente no subsana un requisito habilitante solicitado por la entidad dentro del término legal, la consecuencia jurídica es:", opcionA: "El rechazo definitivo de su propuesta dentro del proceso.", opcionB: "La asignación de cero puntos en el factor económico.", opcionC: "La prórroga automática del proceso por parte del director.", correcta: "Opción A" },
    { enunciado: "La selección del contratista basada exclusivamente en factores técnicos, financieros y jurídicos objetivos responde al principio de:", opcionA: "Selección Objetiva.", opcionB: "Subjetividad Administrativa.", opcionC: "Favoritismo Territorial.", correcta: "Opción A" },
    { enunciado: "El módulo de la plataforma SECOP II donde cualquier ciudadano puede auditar los pliegos, ofertas e informes responde al principio de:", opcionA: "Principio de Reserva Contractual.", opcionB: "Principio de Publicidad.", opcionC: "Principio de Exclusividad Estatal.", correcta: "Opción B" }
    ]
},
{
    estacion: 2, // ESTACIÓN 2: INTERMEDIA (Preguntas 28 a 54 del Excel)
    preguntas: [
    { enunciado: "Durante la etapa precontractual, ¿cuál es el documento definitivo que contiene las reglas de juego, requisitos habilitantes y criterios de ponderación?", opcionA: "Estudio Previo", opcionB: "Matriz de Riesgos", opcionC: "Pliego de Condiciones Definitivo", correcta: "Opción C" },
    { enunciado: "En los procesos de selección de consultoría para interventoría de obras, ¿qué modalidad se debe aplicar obligatoriamente?", opcionA: "Concurso de Méritos", opcionB: "Licitación Pública", opcionC: "Contratación Directa", correcta: "Opción A" },
    { enunciado: "¿Cuál de los siguientes documentos es un soporte financiero obligatorio que ampara la seriedad de las ofertas en una Licitación?", opcionA: "Garantía Única de Cumplimiento", opcionB: "Póliza de Seriedad de la Oferta", opcionC: "Certificado de Disponibilidad Presupuestal", correcta: "Opción B" },
    { enunciado: "La figura jurídica mediante la cual la entidad decide dar por terminado un proceso de selección antes de la adjudicación por razones técnicas o jurídicas sustentadas se denomina:", opcionA: "Revocatoria del Acto de Apertura", opcionB: "Declaratoria de Desierto", opcionC: "Caducidad Contractual", correcta: "Opción A" },
    { enunciado: "¿Qué documento expide la Oficina de Presupuesto para garantizar que la entidad cuenta con los recursos financieros para iniciar un proceso de selección?", opcionA: "Registro Presupuestal (RP)", opcionB: "Certificado de Disponibilidad Presupuestal (CDP)", opcionC: "Plan Anual de Caja (PAC)", correcta: "Opción B" },
    { enunciado: "Cuando en un proceso de Selección Abreviada se presentan demasiados proponentes, ¿qué mecanismo se puede utilizar para limitar el número de ofertas a evaluar?", opcionA: "Sorteo de balotas o Manifestación de Interés", opcionB: "Descalificación por orden de llegada al SECOP", opcionC: "Eliminación automática de propuestas extranjeras", correcta: "Opción A" },
    { enunciado: "¿Qué término legal o traslado se otorga comúnmente para que los proponentes conozcan y controviertan el informe de evaluación en una Licitación Pública?", opcionA: "3 días hábiles", opcionB: "5 días hábiles", opcionC: "10 días calendario", correcta: "Opción B" },
    { enunciado: "Los requisitos habilitantes (como la capacidad jurídica y financiera) dentro de un proceso de selección:", opcionA: "Otorgan puntaje asignable para definir el ganador del proceso", opcionB: "No otorgan puntaje; su cumplimiento es obligatorio para que la oferta sea elegible", opcionC: "Son opcionales y pueden subsanarse incluso después", correcta: "Opción B" },
    { enunciado: "¿A través de qué documento oficial e inmodificable responde la entidad las observaciones presentadas al pliego de condiciones?", opcionA: "Audiencia de Aclaraciones", opcionB: "Documento de Respuesta a Observaciones", opcionC: "Estudio Técnico de Conveniencia", correcta: "Opción B" },
    { enunciado: "El principio de Transparencia exige que los informes de evaluación de propuestas viales sean:", opcionA: "Publicados abiertamente en SECOP II para el control de todos los proponentes.", opcionB: "Enviados bajo reserva de sumario únicamente al proponente ganador.", opcionC: "Destruidos una vez se firme la resolución de adjudicación.", correcta: "Opción A" },
    { enunciado: "Cuando un contrato de obra requiere una modificación que aumenta las cantidades iniciales de obra sin alterar el objeto, se realiza un:", opcionA: "Contrato Adicional en valor y/o cantidades.", opcionB: "Nuevo proceso de licitación pública abreviada.", opcionC: "Acta de suspensión definitiva de actividades.", correcta: "Opción A" },
    { enunciado: "El índice de Endeudamiento exigido en los pliegos tipo como requisito habilitante se calcula como:", opcionA: "Pasivo Total dividido entre el Activo Total.", opcionB: "Activo Corriente menos el Pasivo Corriente.", opcionC: "Utilidad Operacional dividida entre los Gastos Financieros.", correcta: "Opción A" },
    { enunciado: "La garantía de estabilidad de la obra en un contrato de infraestructura vial tiene como fin amparar:", opcionA: "El pago de los salarios y prestaciones sociales de los obreros.", opcionB: "Los daños que sufra la obra por vicios de construcción imputables al contratista tras su entrega.", opcionC: "La seriedad de la propuesta durante la audiencia de adjudicación.", correcta: "Opción B" },
    { enunciado: "La declaratoria de 'Caducidad' de un contrato estatal es una potestad excepcional que la entidad activa cuando:", opcionA: "El contratista incumple gravemente las obligaciones afectando la ejecución y paralizando el servicio.", opcionB: "El contratista solicita de mutuo acuerdo terminar el contrato anticipadamente.", opcionC: "Se acaban los recursos presupuestales asignados para la vigencia fiscal.", correcta: "Opción A" },
    { enunciado: "El Supervisor de un contrato estatal es técnicamente:", opcionA: "Un funcionario de la misma entidad designado para velar por la correcta ejecución del objeto.", opcionB: "Un contratista externo contratado por concurso de méritos para vigilar la obra.", opcionC: "Un delegado de la Contraloría General de la República.", correcta: "Opción A" },
    { enunciado: "El término máximo legal para liquidar un contrato estatal de mutuo acuerdo, si el pliego o contrato no dicen nada, es de:", opcionA: "Cuatro (4) meses siguientes a la fecha de terminación del contrato.", opcionB: "Dos (2) años calendario.", opcionC: "Diez (10) días hábiles improrrogables.", correcta: "Opción A" },
    { enunciado: "La publicación de las respuestas a las observaciones de los pliegos definitivos debe hacerse:", opcionA: "Antes del vencimiento del plazo fijado para la presentación de las ofertas viales.", opcionB: "Durante la misma audiencia pública de adjudicación.", opcionC: "Únicamente si los proponentes lo solicitan mediante derecho de petición.", correcta: "Opción A" },
    { enunciado: "Si en un proceso de Mínima Cuantía se presenta un empate económico exacto entre dos ofertas, el desempate se realiza mediante:", opcionA: "El orden de presentación de las ofertas en la plataforma SECOP II.", opcionB: "Un sorteo por balotas en audiencia virtual obligatoria.", opcionC: "La asignación del contrato al proponente extranjero.", correcta: "Opción A" },
    { enunciado: "La adición de valor a un contrato de interventoría estatal está limitada legalmente a un máximo de:", opcionA: "El 50% de su valor inicial expresado en pesos constantes.", opcionB: "El 100% del presupuesto asignado originalmente.", opcionC: "No tiene límite legal si es para consultorías especializadas.", correcta: "Opción A" },
    { enunciado: "El Registro Único de Proponentes (RUP) es verificado y certificado legalmente en Colombia por:", opcionA: "Las Cámaras de Comercio de cada jurisdicción.", opcionB: "La Subdirección de Procesos de Selección de la entidad.", opcionC: "La Superintendencia de Industria y Comercio.", correcta: "Opción A" },
    { enunciado: "Un contratista estatal que incurre en un incumplimiento grave de sus obligaciones puede ser sancionado con:", opcionA: "Una inhabilidad para contratar con el Estado hasta por cinco (5) años.", opcionB: "La cancelación inmediata de su personería jurídica comercial.", opcionC: "Sanciones disciplinarias internas de la entidad únicamente.", correcta: "Opción A" },
    { enunciado: "El anticipo en un contrato estatal de obra pública se define legalmente como:", opcionA: "Recursos públicos entregados al contratista en calidad de préstamo para financiar la inversión del contrato.", opcionB: "Un pago definitivo que pasa a ser propiedad del contratista desde el primer día.", opcionC: "Un bono de éxito por firmar el acta de inicio de actividades.", correcta: "Opción A" },
    { enunciado: "El documento que detalla el paso a paso de las actividades, frentes de obra y tiempos de ejecución del proyecto se conoce como:", opcionA: "Programa de Ejecución Contractual (Cronograma de Obra).", opcionB: "Matriz de Riesgos Previsibles.", opcionC: "Estudio de Mercado de Precios Unitarios.", correcta: "Opción A" },
    { enunciado: "La modalidad de Selección Abreviada por Subasta Inversa se utiliza principalmente para adquirir:", opcionA: "Bienes y servicios de características técnicas uniformes y de común utilización.", opcionB: "Grandes obras de infraestructura vial como viaductos.", opcionC: "Consultorías especializadas de alta gerencia pública.", correcta: "Opción A" },
    { enunciado: "El principio de Economía en la contratación estatal busca que los procesos se adelanten con:", opcionA: "Austenidad de tiempo, medios y gastos, evitando trámites innecesarios.", opcionB: "El menor uso de materiales técnicos en la obra vial.", opcionC: "La supresión total de los comités técnicos evaluadores.", correcta: "Opción A" },
    { enunciado: "La oferta que sume el mayor puntaje técnico y económico acumulado en una Licitación Pública se considera la:", opcionA: "Oferta más favorable para los intereses de la entidad (Selección Objetiva).", opcionB: "Propuesta con mayor riesgo de incumplimiento contractual.", opcionC: "Única propuesta que puede subsanar sus estados financieros.", correcta: "Opción A" },
    { enunciado: "La firma del Acta de Liquidación Bilateral de un contrato de obra representa:", opcionA: "El finiquito y paz y salvo definitivo entre la entidad y el contratista por los conceptos allí incluidos.", opcionB: "La apertura de la etapa precontractual para las obras complementarias.", opcionC: "La suspensión temporal de las pólizas de estabilidad de la obra.", correcta: "Opción A" }
    ]
},
{
    estacion: 3, // ESTACIÓN 3: AVANZADA (Preguntas 55 a 81 del Excel)
    preguntas: [
    { enunciado: "Los Documentos Tipo adoptados por Colombia Compra Eficiente para procesos de infraestructura de transporte son de aplicación:", opcionA: "Opcional para las entidades del orden nacional y obligatorios para las territoriales.", opcionB: "Obligatorios para todas las entidades estatales que sometan sus procesos a la Ley 80, sin alterar las condiciones habilitantes ni criterios de evaluación.", opcionC: "Exclusivos para contratos cuyo valor sea inferior a la menor cuantía de la respectiva entidad.", correcta: "Opción B" },
    { enunciado: "En un proceso de Selección Abreviada de Menor Cuantía para el mantenimiento de vías urbanas, si se presenta un único proponente que cumple con todo, ¿qué debe hacer la entidad?", opcionA: "Declarar desierto el proceso de forma obligatoria por falta de pluralidad.", opcionB: "Adjudicar el contrato al único proponente calificado, siempre que su oferta cumpla y no supere el presupuesto oficial.", opcionC: "Cancelar el proceso y reiniciarlo bajo la modalidad de contratación directa.", correcta: "Opción B" },
    { enunciado: "La audiencia de asignación de riesgos en los procesos de licitación pública para infraestructura de transporte:", opcionA: "Es un acto opcional que la entidad puede omitir si el comité considera que los riesgos son mínimos.", opcionB: "Es obligatoria y constituye la última oportunidad para que la entidad y los proponentes debatan la distribución de los riesgos antes del cierre.", opcionC: "Se realiza con posterioridad al acto administrativo de adjudicación para acordar las pólizas finales.", correcta: "Opción B" },
    { enunciado: "En la plataforma SECOP II, ¿cómo se materializa la inmutabilidad de las propuestas económicas a partir de la hora de cierre del proceso?", opcionA: "A través del cifrado automático de la plataforma, la cual impide el acceso al módulo de ofertas a la entidad y a terceros hasta la apertura.", opcionB: "Mediante la remisión manuscrita de un código de acceso enviado por el representante legal del proponente.", opcionC: "La plataforma no restringe el acceso, pero la Ley 80 establece sanciones penales si se consulta antes.", correcta: "Opción A" },
    { enunciado: "Si una entidad estatal identifica una tipología o necesidad técnica regional muy específica que no está contemplada en los Pliegos Tipo de CCE para infraestructura vial, ¿puede modificar la experiencia?", opcionA: "Sí, la autonomía territorial consagrada en la Constitución prevalece sobre las circulares.", opcionB: "Sí, siempre que cuente con el visto bueno del Alcalde o Gobernador formalizado mediante decreto.", opcionC: "No, las condiciones de experiencia son inmodificables. Se debe limitar a aplicar las opciones del documento tipo o elevar consulta.", correcta: "Opción C" },
    { enunciado: "¿Qué mecanismo jurídico extingue las obligaciones contractuales y permite realizar el balance financiero final entre INVIAS y el contratista?", opcionA: "La Adición Contractual.", opcionB: "La Liquidación del Contrato.", opcionC: "El Acta de Inicio.", correcta: "Opción B" },
    { enunciado: "En un proceso licitatorio, ¿cuál de los siguientes criterios puede ser utilizado como factor de ponderación (puntuación) y NO como requisito habilitante?", opcionA: "El ofrecimiento de puntaje por vinculación de trabajadores con discapacidad o apoyo a la industria nacional.", opcionB: "La capacidad financiera y organizacional de la empresa.", opcionC: "La existencia jurídica y representación legal de la sociedad proponente.", correcta: "Opción A" },
    { enunciado: "¿Cuándo se entiende formalmente adjudicado un proceso de licitación pública liderado por la Subdirección?", opcionA: "Con la publicación del informe de evaluación técnico definitivo en la plataforma.", opcionB: "Mediante Acto Administrativo motivado (Resolución) proferido en audiencia pública o a través de la plataforma transaccional.", opcionC: "Con la sola firma del contrato físico por parte del Director General.", correcta: "Opción B" },
    { enunciado: "La facultad que tiene la entidad pública para sancionar directamente al contratista mediante la imposición de multas o declaratoria de incumplimiento se deriva de:", opcionA: "Las cláusulas excepcionales y potestades sancionatorias del artículo 17 de la Ley 1150 de 2007.", opcionB: "Un acuerdo informal firmado en el acta de inicio de la obra.", opcionC: "El Código de Comercio exclusivamente.", correcta: "Opción A" },
    { enunciado: "De acuerdo con el Decreto 1082 de 2015, si en un proceso vial se presenta un empate en el puntaje total definitivo entre dos o más ofertas, ¿cuál es el primer criterio legal de desempate?", opcionA: "El proponente que haya acreditado la vinculación del mayor porcentaje de trabajadores con discapacidad.", opcionB: "El orden de radicación o entrega de la propuesta en la plataforma transaccional SECOP II.", opcionC: "Un sorteo por balotas.", correcta: "Opción A" },
    { enunciado: "La Matriz de Riesgos Contractuales en un pliego de condiciones de infraestructura de transporte debe ser publicada obligatoriamente desde:", opcionA: "La publicación de los pliegos de condiciones definitivos únicamente.", opcionB: "La etapa de planeación, acompañando el proyecto de pliego de condiciones y los estudios previos.", opcionC: "El momento de la firma del contrato definitivo para conocimiento del supervisor.", correcta: "Opción B" },
    { enunciado: "Si un proponente omite anexar el certificado RUP actualizado al presentar la oferta en una Licitación, ¿qué naturaleza jurídica tiene este documento?", opcionA: "Causa de rechazo automático e insubsanable de la propuesta por afectar la seriedad de la oferta.", opcionB: "Es un documento de naturaleza subsanable, por lo que la entidad debe solicitarlo durante el traslado de evaluaciones.", opcionC: "No es necesario subsanarlo, la entidad puede omitir la revisión financiera.", correcta: "Opción B" },
    { enunciado: "Las adiciones en valor para los contratos estatales viales, según lo establecido en el parágrafo del artículo 40 de la Ley 80 de 1993, no podrán exceder:", opcionA: "El cincuenta por ciento (50%) de su valor inicial, expresado en salarios mínimos legales mensuales.", opcionB: "El cincuenta por ciento (50%) de su valor inicial, reajustado por la inflación o el IPC.", opcionC: "El treinta por ciento (30%) de su valor inicial, sin importar las obras complementarias.", correcta: "Opción B" },
    { enunciado: "El principio de Planeación en la contratación estatal implica que la Subdirección no puede abrir un proceso de selección sin contar previamente con:", opcionA: "Los diseños, estudios y análisis técnicos, económicos y jurídicos definitivos que sustenten la viabilidad del proyecto.", opcionB: "El listado de los nombres de los futuros subcontratistas que ejecutaran la obra vial.", opcionC: "La aprobación del proyecto por parte de la Jurisdicción de lo Contencioso Administrativo.", correcta: "Opción A" },
    { enunciado: "En los pliegos de condiciones para infraestructura de transporte, el indicador financiero de 'Índice de Liquidez' mide:", opcionA: "La capacidad de la empresa para cumplir con sus obligaciones a corto plazo (Activo Corriente / Pasivo Corriente).", opcionB: "El nivel de endeudamiento total del proponente frente a sus activos fijos no corrientes.", opcionC: "La rentabilidad neta del patrimonio generada durante el último año fiscal auditado.", correcta: "Opción A" },
    { enunciado: "La 'Urgencia Manifiesta' es una figura jurídica excepcional que permite la contratación directa cuando:", opcionA: "La entidad no alcanzó a planear el proceso en el PAA y se vence el año fiscal.", opcionB: "Se presentan situaciones de fuerza mayor, desastres naturales o calamidades que exijan la continuidad inmediata del servicio.", opcionC: "El Director General lo determine de manera discrecional sin necesidad de acto administrativo.", correcta: "Opción B" },
    { enunciado: "El documento mediante el cual el supervisor o interventor de un contrato vial certifica que el contratista cumplió a satisfacción con el objeto pactado se denomina:", opcionA: "Acta de Suspensión Contractual.", opcionB: "Acta de Recibo Definitivo u Obra Terminada.", opcionC: "Acta de Liquidación Bilateral Unilateral.", correcta: "Opción B" },
    { enunciado: "Si un proponente presenta una oferta económica que resulta artificialmente baja frente a los análisis de costos de la entidad, ¿qué debe hacer el comité evaluador?", opcionA: "Rechazar la propuesta inmediatamente por sospecha de inviabilidad técnica.", opcionB: "Requerir al proponente para que explique y sustente los costos de su oferta antes de proceder a un posible rechazo.", opcionC: "Asignarle el máximo puntaje económico de manera automática por economía procesal.", correcta: "Opción B" },
    { enunciado: "La tipología contractual aplicable cuando la Subdirección requiere contratar estudios geotécnicos o diseños hidráulicos específicos para una vía es:", opcionA: "Contrato de Obra Pública.", opcionB: "Contrato de Consultoría.", opcionC: "Contrato de Prestación de Servicios de Apoyo a la Gestión.", correcta: "Opción B" },
    { enunciado: "La publicación de los actos administrativos en el SECOP II, de acuerdo con el principio de Publicidad, es un requisito esencial para:", opcionA: "La eficacia y oponibilidad de las decisiones de la entidad frente a los proponentes y la ciudadanía.", opcionB: "La validez interna del presupuesto de la nación únicamente.", opcionC: "Evitar que los proponentes presenten recursos legales en contra de la adjudicación.", correcta: "Opción A" },
    { enunciado: "El control preferente que ejerce la Procuraduría General de la Nación en las etapas previas de los procesos licitatorios viales tiene una naturaleza de:", opcionA: "Acompañamiento preventivo, el cual no coadministra ni suspende los términos autonómicos de la entidad.", opcionB: "Aprobación vinculante obligatoria para poder adjudicar el contrato final.", opcionC: "Auditoría postcontractual enfocada exclusivamente en el balance financiero.", correcta: "Opción A" },
    { enunciado: "La figura de la 'Garantía Única de Cumplimiento' en los contratos de obra pública del INVIAS tiene como objeto principal:", opcionA: "Financiar el flujo de caja del contratista durante los primeros meses de ejecución.", opcionB: "Amparar los perjuicios derivados del incumplimiento, la estabilidad de la obra y el pago de salarios.", opcionC: "Garantizar que el proponente mantendrá el precio de su oferta durante el término de traslado.", correcta: "Opción B" },
    { enunciado: "Durante la etapa precontractual, ¿por cuántos días hábiles se debe dejar el Informe de Evaluación a disposición de los proponentes en una Licitación?", opcionA: "Por 5 días hábiles (Término de traslado).", opcionB: "Por 1 día calendario.", opcionC: "No es necesario publicarlo, se notifica directamente al ganador.", correcta: "Opción A" },
    { enunciado: "¿Cuál es el acto administrativo definitivo con el cual la entidad estatal formaliza la elección del ganador del proceso de Licitación Pública?", opcionA: "La Firma del Acta de Inicio de la vía.", opcionB: "La Declaratoria de Desierto del proceso.", opcionC: "El Acto Administrativo de Adjudicación.", correcta: "Opción C" },
    { enunciado: "¿Bajo qué causal se puede declarar 'Desierto' un proceso de selección de infraestructura en la etapa precontractual?", opcionA: "Cuando el presupuesto de la entidad aumenta a mitad de camino.", opcionB: "Cuando ninguna de las ofertas presentadas cumple con los requisitos habilitantes y esenciales exigidos en el pliego.", opcionC: "Cuando se presentan más de 10 proponentes al proceso.", correcta: "Opción B" },
    { enunciado: "El Plan Anual de Adquisiciones (PAA) es una herramienta precontractual que sirve para:", opcionA: "Planear y publicar las compras y obras que la entidad estatal pretende contratar durante el año.", opcionB: "Modificar los contratos vigentes del año anterior.", opcionC: "Liquidar los convenios que salieron mal.", correcta: "Opción A" },
    { enunciado: "En materia de contratación estatal, el uso del SECOP II promueve principalmente el principio de:", opcionA: "Secreto comercial entre contratistas viales.", opcionB: "Transparencia y publicidad, al permitir el control ciudadano sobre los recursos y el avance del proceso.", opcionC: "Subjetividad en la contratación pública.", correcta: "Opción B" }
    ]
}
];